### ISSUE TITLE
您好，我希望可以转载您的作品

### ISSUE THREAD

**Issue by Brick-web** [teaconmc/xibao#4]
您好，我希望可以转载您的作品到我都开放博客中，我会在文章头部明显标注您的GitHub项目地址，GitHub个人主页地址以及您的名称，希望可以得到您的同意，感谢

**Comment by 3TUSK** [comment]
关于这方面的问题，还请阅读本项目的 license (https://github.com/teaconmc/xibao/blob/1.18-forge/LICENSE) 了解详细信息。

**Comment by Brick-web** [comment]
> 关于这方面的问题，还请阅读本项目的 license （https://github.com/teaconmc/xibao/blob/1.18-forge/LICENSE） 了解详细信息。

感谢
